import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";

import "./styles/globals.css";
import dynamic from "next/dynamic";
const TopBar = dynamic(() => import("./components/top-bar"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Stock Controller",
  description: "Generated by Innovation/Exploration team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <body>
            <TopBar />
            {children}
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
